### ISSUE TITLE
Creating Large Lists Causes an Engine Crash

### ISSUE THREAD

**Issue by pashneal** [battlecode/battlehack20#90]
```python

from battlehack20.stubs import *
def turn():

   from battlehack20.stubs import *
def turn():
    #list initialized to 300 elements
    sequences = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    bytecode = get_bytecode()

```
The get_bytecode() function gracelessly exits the program with the following error
```
Traceback (most recent call last):
  File "../run.py", line 97, in <module>
    code_container0 = CodeContainer.from_directory(args.player[0])
  File "/home/user/.local/lib/python2.6/site-packages/battlehack20/engine/container/code_container.py", line 34, in from_directory
    return cls.from_directory_dict(code)
  File "/home/user/.local/lib/python2.6/site-packages/battlehack20/engine/container/code_container.py", line 21, in from_directory_dict
    code[module_name] = Instrument.instrument(compiled)
  File "/home/user/.local/lib/python2.6/site-packages/battlehack20/engine/container/instrument.py", line 37, in instrument
    new_consts.append(Instrument.instrument(constant))
  File "/home/user/.local/lib/python2.6/site-packages/battlehack20/engine/container/instrument.py", line 170, in instrument
    new_lnotab[old_to_new_instruction_num[key]] = old_lnotab[key]
KeyError: 254
```

**Comment by pashneal** [comment]
If a player is losing and sees no way to win they can (presumably) force quit the game by doing this .

**Comment by arvid220u** [comment]
@majabbour seems related to line numbers?

**Comment by DE4BF148** [comment]
> If a player is losing and sees no way to win they can (presumably) force quit the game by doing this .

The players never take their turns, so this can't be used to "force quit" from a losing game.

**Comment by pashneal** [comment]
Thanks for the correction!
